language: cpp
sudo: required

matrix:
  include:
    # Linux and GCC
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        - CC_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
      script:
        - cmake --version
        - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
        - sudo apt-get update
        - sudo apt-get install intel-mkl-64bit-2017.4-061
        - source /opt/intel/mkl/bin/mklvars.sh intel64
        - source /opt/intel/bin/compilervars.sh intel64
        - git submodule init
        - git submodule update
        - cd IsoStuffer
        - mkdir build
        - cd build
        - CC=$CC_COMPILER CXX=$CXX_COMPILER cmake ..
        - make -j 2
        - cd ../../ModalSound/
        - chmod 755 get_eigen.sh
        - ./get_eigen.sh
        - chmod 755 get_libqglviewer.sh
        - ./get_qglviewer.sh
        - mkdir build
        - cd build
        - CC=$CC_COMPILER CXX=$CXX_COMPILER cmake ..
        - make -j 2
      #  - $CTEST_EXEC -j 2 --output-on-failure
      #     - os: osx
      #       compiler: clang
      #       script:
      #         - cmake --version
      #         - git submodule init
      #         - git submodule update
      #         - mkdir build
      #         - cd build
      #         - cmake ..
      #         - make -j 2

before_install:
  # Workaround for weird Python binary in the latest Travis CI update
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/usr/bin/:$PATH ; fi
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake cmake-data git libboost-all-dev xorg-dev libglu1-mesa-dev libgoogle-glog-dev freeglut3-dev qtmultimedia5-dev  qt5-default mesa-utils  libxmu-dev libxi-dev libconfig++-dev libprotobuf-dev libgsl0ldbl protobuf-compiler libgsl0-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update > /dev/null ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake ; fi
  # only for debuging
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake vim git; fi
  # it appears that boost has been installed, with at least version 1.61, so
  # a pretty new version.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install eigen glog gflags libconfig; fi
    
